export const orgData = {
  president: {
    id: "pres-001",
    title: "Président du Conseil d'École",
    name: "",
    icon: "👔",
    level: 1,
    description: "Préside le Conseil d'École et définit la direction stratégique de l'établissement.",
    responsibilities: [
      "Fixer la vision de l'école",
      "Gérer les relations avec le Conseil",
      "Assurer la performance globale",
      "Diriger les initiatives majeures",
    ],
    reportsTo: "Conseil d'École",
    teamSize: 1,
  },
  directorGeneral: {
    id: "dir-dg",
    title: "Directeur",
    name: "",
    icon: "🎓",
    level: 2,
    department: "Direction",
    description: "Dirige les opérations académiques et administratives de l'établissement.",
    responsibilities: [
      "Gérer les opérations académiques",
      "Superviser l'administration générale",
      "Assurer la qualité pédagogique",
      "Diriger l'équipe de direction",
    ],
    reportsTo: "Président du Conseil d'École",
    teamSize: 15,
  },
  directors: [
    {
      id: "dir-001",
      title: "Responsable Mention",
      name: "",
      icon: "📚",
      level: 3,
      department: "Académique",
      description: "Responsable de la gestion académique et pédagogique de sa mention.",
      responsibilities: [
        "Superviser les formations",
        "Gérer les programmes académiques",
        "Assurer la qualité pédagogique",
        "Coordonner les enseignants",
      ],
      reportsTo: "Directeur",
      teamSize: 6,
    },
    {
      id: "dir-002",
      title: "Assesseurs",
      name: "",
      icon: "⚖️",
      level: 3,
      department: "Académique",
      description: "Assistants du Directeur pour les questions académiques et pédagogiques.",
      responsibilities: [
        "Assister le Directeur",
        "Superviser les examens",
        "Gérer les disciplines",
        "Coordonner les projets",
      ],
      reportsTo: "Directeur",
      teamSize: 4,
    },
    {
      id: "dir-003",
      title: "CEMP",
      name: "",
      icon: "🏫",
      level: 3,
      department: "Académique",
      description: "Commission d'Étude des Moyens Pédagogiques.",
      responsibilities: [
        "Évaluer les moyens pédagogiques",
        "Proposer des améliorations",
        "Coordonner les ressources",
        "Assurer la qualité",
      ],
      reportsTo: "Directeur",
      teamSize: 3,
    },
  ],
  managers: [
    {
      id: "mgr-001",
      title: "PRMP",
      name: "",
      icon: "📋",
      level: 4,
      department: "Administration",
      description: "Responsable de l'administration générale et de la gestion administrative.",
      responsibilities: [
        "Gérer l'administratif",
        "Superviser la documentation",
        "Coordonner les dossiers",
        "Assurer la conformité",
      ],
      reportsTo: "Directeur",
      teamSize: 2,
    },
    {
      id: "mgr-002",
      title: "Secrétaire Principal",
      name: "",
      icon: "🖊️",
      level: 4,
      department: "Administration",
      description: "Responsable des fonctions de secrétariat et de la gestion administrative.",
      responsibilities: [
        "Gérer le secrétariat général",
        "Coordonner la documentation",
        "Superviser le personnel administratif",
        "Organiser les événements",
      ],
      reportsTo: "Directeur",
      teamSize: 5,
    },
    {
      id: "mgr-003",
      title: "Dépositaire Comptable",
      name: "",
      icon: "💼",
      level: 4,
      department: "Finance",
      description: "Responsable de la gestion financière et comptable de l'établissement.",
      responsibilities: [
        "Gérer les finances",
        "Superviser la comptabilité",
        "Contrôler les budgets",
        "Assurer la conformité fiscale",
      ],
      reportsTo: "Directeur",
      teamSize: 3,
    },
  ],
  assistants: [
    {
      id: "asst-001",
      title: "Agent Payeur",
      name: "",
      icon: "💳",
      level: 5,
      department: "Finance",
      description: "Responsable de la gestion des salaires et des paiements.",
      responsibilities: ["Gérer les salaires", "Traiter les paiements", "Superviser la paie", "Gérer les arrérages"],
      reportsTo: "Secrétaire Principal",
      teamSize: 1,
    },
  ],
  services: [
    {
      id: "svc-001",
      title: "SAG",
      name: "Service des Affaires Générales",
      icon: "📁",
      level: 6,
      parentId: "mgr-001",
    },
    {
      id: "svc-002",
      title: "SPERS",
      name: "Service du Personnel",
      icon: "👥",
      level: 6,
      parentId: "mgr-002",
    },
    {
      id: "svc-003",
      title: "SCOMPTA",
      name: "Service de la Comptabilité",
      icon: "💰",
      level: 6,
      parentId: "mgr-003",
    },
    {
      id: "svc-004",
      title: "SDE & Scolarité",
      name: "Service Des Étudiants et de la Scolarité",
      icon: "🎓",
      level: 6,
      parentId: "dir-001",
    },
    {
      id: "svc-005",
      title: "SPat",
      name: "Service du Patrimoine",
      icon: "🏛️",
      level: 6,
      parentId: "mgr-001",
    },
    {
      id: "svc-006",
      title: "SDBN",
      name: "Service de la Documentation et Bibliothèque Numérique",
      icon: "📚",
      level: 6,
      parentId: "mgr-002",
    },
    {
      id: "svc-007",
      title: "Magasinier",
      name: "Service de Gestion des Stocks",
      icon: "📦",
      level: 6,
      parentId: "mgr-001",
    },
    {
      id: "svc-008",
      title: "Bloc Technique",
      name: "Division Technique",
      icon: "🔧",
      level: 6,
      parentId: "mgr-002",
      hasSubServices: true,
    },
    {
      id: "svc-009",
      title: "Atelier Luban",
      name: "Service d'Ateliers Techniques",
      icon: "⚒️",
      level: 6,
      parentId: "dir-001",
    },
    {
      id: "svc-010",
      title: "Réseaux et SI",
      name: "Service des Réseaux et Systèmes d'Information",
      icon: "🌐",
      level: 6,
      parentId: "mgr-001",
    },
    {
      id: "svc-011",
      title: "SCOM",
      name: "Service de la Communication",
      icon: "📢",
      level: 6,
      parentId: "mgr-001",
    },
    {
      id: "svc-012",
      title: "SRIP",
      name: "Service des Relations Internationales et du Partenariat",
      icon: "🌍",
      level: 6,
      parentId: "dir-002",
    },
  ],
  subServices: [
    {
      id: "subsvc-001",
      title: "DMA",
      name: "Division Maintenance et Automobile",
      icon: "🚗",
      level: 7,
      parentId: "svc-008",
    },
    {
      id: "subsvc-002",
      title: "DTBT",
      name: "Division Technique du Bloc Technique",
      icon: "🔩",
      level: 7,
      parentId: "svc-008",
    },
    {
      id: "subsvc-003",
      title: "IM",
      name: "Ingénieur Mécanicien",
      icon: "⚙️",
      level: 7,
      parentId: "svc-008",
    },
    {
      id: "subsvc-004",
      title: "EI & TI",
      name: "Électricité Industrielle et Technologie de l'Information",
      icon: "⚡",
      level: 7,
      parentId: "svc-008",
    },
    {
      id: "subsvc-005",
      title: "DMR",
      name: "Division Maintenance et Réseaux",
      icon: "🖧",
      level: 7,
      parentId: "svc-008",
    },
    {
      id: "subsvc-006",
      title: "DDSI",
      name: "Division Développement et Système d'Information",
      icon: "💻",
      level: 7,
      parentId: "svc-008",
    },
  ],
}
